In [3]:
import pandas as pd

filename = "BA_23FS_Curdin_Fitze_5_7_9_11_13_TSextract.xlsx"

import_excel = pd.read_excel(filename, sheet_name="15min")

options=[{'label': column, 'value': column} for column in import_excel.columns[1:]],

print("Columns: {}".format(options))

swiss_time_format = '%dd.%m.%YY'
print(swiss_time_format)



# matplotlib tk

columns = import_excel.columns.tolist()

print("columns: {}".format(columns))

datasets = import_excel[columns].keys()  # Get the available datasets

initial_selected_columns = [columns[0], columns[1]]  # Set the initial selected columns

print("Initial selected columns: {}".format(initial_selected_columns))
print("Initial selected columns data type: {}".format(type(initial_selected_columns)))


print


options = []
for column in initial_selected_columns:
    selected_columns= import_excel[column]  # Get the data for the selected column
    options.extend([{'label': column, 'value': column} for column in initial_selected_columns])

print("Selected Columns: {}".format(options))


print("datasets: {}".format(datasets))

# options=[{'label': column, 'value': column} for column in columns]

# print("options: {}".format(columns))

# filtered_data = import_excel_figure['data']
filtered_data = import_excel

# Filter the data based on the selected date range
filtered_data_items = filtered_data.items()



# for key, value in filtered_data_items:
#     print(f"Key: {key}")
#     print(f"Value:\n{value}\n")

# print("Data items: {}".format(filtered_data_items))


# startdate

# Filter the data based on the selected date range
# filtered_data = {date: data for date, data in filtered_data.items() if start_date <= date <= end_date}

# Convert DateTime column to datetime format
datetime_column = pd.to_datetime(import_excel['DateTime'])

selected_date_range = (10,20)

start_date_index, end_date_index = selected_date_range
start_date = datetime_column[start_date_index]
end_date = datetime_column[end_date_index]

# Filter the data based on the selected date range
filtered_data_dates_x = datetime_column[(datetime_column >= start_date) & (datetime_column <= end_date)]

print("Choose Date Range: {}".format(filtered_data_dates_x))

Dictionary columns ([{'label': 'Solar [kWh]', 'value': 'Solar [kWh]'}, {'label': 'SelfConsumption [kWh]', 'value': 'SelfConsumption [kWh]'}, {'label': 'Demand [kWh]', 'value': 'Demand [kWh]'}, {'label': 'Net Grid Import/Export [kWh]', 'value': 'Net Grid Import/Export [kWh]'}, {'label': 'Battery [kWh]', 'value': 'Battery [kWh]'}, {'label': 'Revenue', 'value': 'Revenue'}, {'label': 'Savings', 'value': 'Savings'}, {'label': 'NetBenefit', 'value': 'NetBenefit'}, {'label': 'TotalProduced', 'value': 'TotalProduced'}, {'label': 'SolarToNet', 'value': 'SolarToNet'}, {'label': 'Total Incident Radiation [MWh]', 'value': 'Total Incident Radiation [MWh]'}, {'label': 'Solar DC [kWh]', 'value': 'Solar DC [kWh]'}, {'label': 'PVTariff', 'value': 'PVTariff'}, {'label': 'Eprice', 'value': 'Eprice'}],)
%dd.%m.%YY
columns: ['DateTime', 'Solar [kWh]', 'SelfConsumption [kWh]', 'Demand [kWh]', 'Net Grid Import/Export [kWh]', 'Battery [kWh]', 'Revenue', 'Savings', 'NetBenefit', 'TotalProduced', 'SolarToNet', 'Total Incident Radiation [MWh]', 'Solar DC [kWh]', 'PVTariff', 'Eprice']
Initial selected columns: ['DateTime', 'Solar [kWh]']
Initial selected columns data type: <class 'list'>
Selected Columns: [{'label': 'DateTime', 'value': 'DateTime'}, {'label': 'Solar [kWh]', 'value': 'Solar [kWh]'}, {'label': 'DateTime', 'value': 'DateTime'}, {'label': 'Solar [kWh]', 'value': 'Solar [kWh]'}]
datasets: Index(['DateTime', 'Solar [kWh]', 'SelfConsumption [kWh]', 'Demand [kWh]',
       'Net Grid Import/Export [kWh]', 'Battery [kWh]', 'Revenue', 'Savings',
       'NetBenefit', 'TotalProduced', 'SolarToNet',
       'Total Incident Radiation [MWh]', 'Solar DC [kWh]', 'PVTariff',
       'Eprice'],
      dtype='object')
Choose Date Range: 10   2023-01-01 02:30:00
11   2023-01-01 02:45:00
12   2023-01-01 03:00:00
13   2023-01-01 03:15:00
14   2023-01-01 03:30:00
15   2023-01-01 03:45:00
16   2023-01-01 04:00:00
17   2023-01-01 04:15:00
18   2023-01-01 04:30:00
19   2023-01-01 04:45:00
20   2023-01-01 05:00:00
Name: DateTime, dtype: datetime64[ns]

In [8]:
# subset_months = datetime_column[datetime_column.dt.year == 2023].dt.month

# month_names = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

# marks={i: {'label': month_names[i-1]} for i in month_names},

month_names = ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']

# Update the code to use German month names
marks = {i: {'label': month_names[i-1]} for i in range(1, 13)}
print(marks)

{1: {'label': 'Januar'}, 2: {'label': 'Februar'}, 3: {'label': 'März'}, 4: {'label': 'April'}, 5: {'label': 'Mai'}, 6: {'label': 'Juni'}, 7: {'label': 'Juli'}, 8: {'label': 'August'}, 9: {'label': 'September'}, 10: {'label': 'Oktober'}, 11: {'label': 'November'}, 12: {'label': 'Dezember'}}

In [5]:
import_excel.describe()

,Solar [kWh],SelfConsumption [kWh],Demand [kWh],Net Grid Import/Export [kWh],Battery [kWh],Revenue,Savings,NetBenefit,TotalProduced,SolarToNet,Total Incident Radiation [MWh],Solar DC [kWh],PVTariff,Eprice
count,35037.000000,35037.000000,35037.000000,35037.000000,35037.000000,35037.000000,35037.000000,35037.000000,35037.000000,35037.000000,34205.000000,3.503700e+04,35037.000000,35037.000000
mean,3.929687,1.575766,2.575057,2.319564,0.034358,0.422812,0.120469,0.543281,3.929687,2.319564,0.023230,3.940119e+00,0.157507,0.067680
std,6.355488,1.936869,1.955545,5.195723,1.749089,0.940304,0.150873,0.996563,6.355488,5.195723,0.036982,6.339813e+00,0.025760,0.013503
min,-0.025000,0.000000,0.524375,-0.210484,-8.925040,0.000000,0.000000,0.000000,-0.025000,-0.210484,0.000000,-2.461742e-50,0.129500,0.053000
25%,-0.025000,0.000000,1.123750,-0.025000,0.000000,0.000000,0.000000,0.000000,-0.025000,-0.025000,0.000000,0.000000e+00,0.129500,0.053000
50%,-0.025000,0.798750,1.743750,-0.025000,0.000000,0.000000,0.057683,0.063874,-0.025000,-0.025000,0.000000,2.969693e-48,0.181200,0.080100
75%,5.498650,2.649989,3.822500,0.000000,0.000000,0.000000,0.197616,0.422566,5.498650,0.000000,0.032438,5.487924e+00,0.181200,0.080100
max,25.000000,10.284375,12.767500,24.025122,14.384020,4.353352,0.823778,4.412787,25.000000,24.025122,0.154385,2.625438e+01,0.181200,0.080100

In [ ]:
import_excel.plot(x="DateTime", y="Solar [kWh]")

In [ ]:
dt = import_excel["DateTime"].values
solar = import_excel["Solar [kWh]"].values

In [ ]:
import matplotlib.pyplot as plt

plt.plot(dt, solar)